organisation:
  ods_code: TAD

team:
  name: Locala sub-contract to Bradford District Trust - Bradford
  workgroup: bradfordmavisnr
  type: national_reporting
  national_reporting_cut_off_date: 2026-05-11
