organisation:
  ods_code: RY5

team:
  name: Lincolnshire Community Health Services NHS Trust
  workgroup: lincolnshiremavisnr
  type: national_reporting
  national_reporting_cut_off_date: 2026-06-01
