organisation:
  ods_code: Z5L3C

team:
  name: Locala sub-contract to Bradford District Trust - Wakefield
  workgroup: wakefieldmavisnr
  type: national_reporting
  national_reporting_cut_off_date: 2026-05-11
