---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

:queues:
  - cache
  - imports
  - consents
  - notifications
  - patients
  - triages
  - pds
  - immunisations_api_sync
  - immunisations_api_search
  - third_party_data_imports
  - careplus
  - metrics
  - default

:scheduler:
  :schedule:
    # Half-hourly
    Metrics::ExportSchoolMovesCountJob:
      every: 30m
      description: Export school moves count metric

    # Hourly
    ReportingAPI::RefreshJob:
      cron: "0 * * * *"
      description: Refresh the reporting API materialized view data

    # 6-hourly
    EnqueueUpdatePatientsFromPDSJob:
      cron: "0 0,6,12,18 * * *"
      description: Keep patient details up to date with PDS

    # Each afternoon and evening
    SendVaccinationConfirmationsJob:
      cron: "0 13,16,19 * * *"
      description: Send vaccination confirmation emails to parents

    # Nightly
    EnqueueLocationPositionUpdaterJob:
      cron: "0 0 * * *"
      description:
        Enqueue jobs to fetch latitude and longitude for locations with addresses but no position
    RemoveImportCSVJob:
      cron: "0 1 * * *"
      description: Remove CSV data from old cohort and immunisation imports
    GIASImportJob:
      cron: "30 1 * * *"
      description: Download and import GIAS data
    InvalidateSelfConsentsJob:
      cron: "0 2 * * *"
      description: Invalidate all self-consents and associated triage for the previous day
    TrimActiveRecordSessionsJob:
      cron: "0 2 * * *"
      description: Remove ActiveRecord sessions older than 30 days
    EnqueueAutomatedCareplusReportsJob:
      cron: "30 2 * * *"
      description: Enqueue automated CarePlus reports for teams with CarePlus configured
    PatientStatusUpdaterJob:
      cron: "0 3 * * *"
      description: Updates the status of all patients
    EnqueueProcessUnmatchedConsentFormsJob:
      cron: "0 4 * * *"
      description: Re-process unmatched consent forms to attempt automatic matching
    RemoveExportFileDataJob:
      cron: "0 4 * * *"
      description: Purge old vaccination report exports and mark expired
    EnqueuePatientsAgedOutOfSchoolsJob:
      cron: "0 5 * * *"
      description: Moves patients who have aged out of their school to unknown school
    PatientsClearRegistrationJob:
      cron: "15 5 * * *"
      description: Clears the registration of patients for the previous academic year
    PatientsRefusedConsentAlreadyVaccinatedJob:
      cron: "30 5 * * *"
      description: >-
        Record already vaccinated for patients who refused consent in the previous academic year for
        that reason
    EnqueueVaccinationsSearchInNHSJob:
      cron: "0 6 * * *"
      description: Find upcoming sessions and enqueue jobs to find vaccinations for patients in them

    # Daily
    EnqueueSchoolSessionRemindersJob:
      cron: "0 9 * * *"
      description: Send school session reminder emails to parents
    EnqueueSchoolConsentRequestsJob:
      cron: "0 16 * * *"
      description: Send school consent request emails to parents for each session
    EnqueueSchoolConsentRemindersJob:
      cron: "15 16 * * *"
      description: Send school consent reminder emails to parents for each session
